#查看springboot开启了哪些配置
debug: false
spring:
  profiles:
    active: dev

#mybatis:
#  mapper-locations: classpath*:mappings/*Dao.xml
#  type-aliases-package: com.yangmiemie.ele.entity,com.yangmiemie.ele.common.vo

logging:
    level:  # 日志级别
        org.springframework.web: DEBUG # 配置spring web日志级别
        org.apache.http: warn
        org.apache.http.wire: warn